# Generated by Django 5.2.9 on 2026-01-27 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_orderitem'),
        ('result', '0003_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='result.enrollment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('momo', 'MoMo Wallet'), ('free', 'Free Enrollment')], max_length=20),
        ),
    ]
