# Generated by Django 5.2.9 on 2026-05-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_businesslead_request_type'),
        ('payments', '0003_alter_transaction_enrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan_upgrade', models.CharField(choices=[('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='PRO', max_length=20)),
                ('payment_proof', models.FileField(help_text='Bank transfer receipt or invoice copy', upload_to='b2b_receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Reason for rejection or internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_payments', to='organization.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
