# Generated by Django 5.2.9 on 2026-05-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_b2bpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_pdf_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('enterprise', 'Enterprise')], default='retail', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
