# Generated by Django 5.2.9 on 2026-05-04 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_course_instructor_lecture_deleted_at_and_more'),
        ('payments', '0005_order_company_address_order_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2bpayment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_payments', to='course.course'),
        ),
        migrations.AddField(
            model_name='b2bpayment',
            name='payment_type',
            field=models.CharField(choices=[('UPGRADE', 'Plan Upgrade'), ('COURSE', 'Course Bulk Purchase')], default='UPGRADE', max_length=20),
        ),
        migrations.AddField(
            model_name='b2bpayment',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='b2bpayment',
            name='plan_upgrade',
            field=models.CharField(blank=True, choices=[('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='PRO', max_length=20, null=True),
        ),
    ]
