# Generated by Django 5.2.9 on 2026-01-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_businesslead'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslead',
            name='request_type',
            field=models.CharField(choices=[('CONTACT', 'General Inquiry'), ('DEMO', 'Demo Request')], default='CONTACT', max_length=20),
        ),
    ]
