# Generated by Django 5.2.9 on 2026-02-08 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('course', 'Course Announcement'), ('learning', 'Bình luận/Hỏi đáp'), ('review', 'New Review'), ('enrollment', 'New Enrollment')], default='system', max_length=20)),
                ('link', models.CharField(blank=True, help_text='Link to relevant resource (e.g. /course/slug)', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='core_notifi_recipie_4d7e73_idx'), models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx')],
            },
        ),
    ]
