# Generated by Django 5.2.9 on 2026-01-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_category_options_alter_category_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_vi',
            field=models.CharField(blank=True, help_text='Vietnamese name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_vi',
            field=models.TextField(blank=True, help_text='Vietnamese description', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle_vi',
            field=models.CharField(blank=True, help_text='Vietnamese subtitle', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_vi',
            field=models.CharField(blank=True, help_text='Vietnamese title', max_length=200, null=True),
        ),
    ]
