# Generated by Django 5.2.9 on 2026-01-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_category_name_vi_course_description_vi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requirements_vi',
            field=models.JSONField(blank=True, default=list, help_text='Vietnamese requirements'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience_vi',
            field=models.JSONField(blank=True, default=list, help_text='Vietnamese target audience'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn_vi',
            field=models.JSONField(blank=True, default=list, help_text='Vietnamese learning outcomes'),
        ),
    ]
