# Generated by Django 5.2.9 on 2026-01-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Admin control to hide course'),
        ),
    ]
