# Generated by Django 5.2.9 on 2026-01-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='article_content',
            field=models.TextField(blank=True, help_text='Main content for Article type (Markdown supported)'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='asset_id',
            field=models.CharField(blank=True, help_text='External ID or S3 Key', max_length=255),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('file', 'File/Resource'), ('quiz', 'Quiz')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('processing', 'Processing')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_source',
            field=models.CharField(blank=True, choices=[('upload', 'Direct Upload'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('external', 'External URL')], default='upload', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.TextField(blank=True, help_text='Short description or summary'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='resources',
            field=models.JSONField(blank=True, default=list, help_text='Downloadable resources (legacy)'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL for YouTube/Vimeo or public file'),
        ),
    ]
