# Generated by Django 5.2.9 on 2026-01-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_status_alter_lecture_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Internal admin notes/rejection reason'),
        ),
    ]
