# Generated by Django 5.2.9 on 2026-01-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_lecture_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled publish time', null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, help_text='Direct video file upload', null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('paused', 'Paused'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('scheduled', 'Scheduled'), ('processing', 'Processing')], default='draft', max_length=20),
        ),
    ]
