# Generated by Django 5.2.9 on 2026-01-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_lecture_published_at_lecture_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
