# Generated by Django 5.2.9 on 2026-01-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_deleted_at_course_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='congratulations_message',
            field=models.TextField(blank=True, help_text='Message sent to students upon completion'),
        ),
        migrations.AddField(
            model_name='course',
            name='welcome_message',
            field=models.TextField(blank=True, help_text='Message sent to students upon enrollment'),
        ),
    ]
