# Generated by Django 5.2.9 on 2026-04-25 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('course', '0014_remove_course_instructor_lecture_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='context_used',
            field=models.TextField(blank=True, help_text='RAG Context used', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response_time_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='course.course'),
        ),
    ]
