# Generated by Django 5.2.9 on 2026-01-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='badge_image_url',
            field=models.URLField(blank=True, help_text='URL to the official certification badge', null=True),
        ),
    ]
