# Generated by Django 5.2.9 on 2026-05-02 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField(help_text='Professional qualifications, degrees, and teaching experience')),
                ('certifications', models.FileField(blank=True, help_text='PDF or Image of relevant certifications', null=True, upload_to='instructor_applications/certs/')),
                ('demo_video', models.FileField(blank=True, help_text='Short demo teaching video', null=True, upload_to='instructor_applications/demos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_update', 'Needs Update')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Reason for rejection or request for more information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
