# Generated by Django 5.2 on 2025-05-12 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("credit", models.IntegerField()),
                ("semester", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ResultTakenCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment", models.FloatField()),
                ("mid_exam", models.FloatField()),
                ("quiz", models.FloatField()),
                ("attendance", models.FloatField()),
                ("final_exam", models.FloatField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_taken_courses",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
