# Generated by Django 5.2.9 on 2026-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_instructorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_business',
            field=models.BooleanField(default=False, help_text='Business/Enterprise user'),
        ),
    ]
