# Generated by Django 5.2.9 on 2026-01-14 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_instructor_approved',
            field=models.BooleanField(default=False, verbose_name='Instructor Approved'),
        ),
        migrations.CreateModel(
            name='InstructorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why do you want to become an instructor?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
